#!/bin/bash

sudo pacman -S --noconfirm --needed ripgrep xclip 


if [ -d "~/tools-personal/fzf" ]; then
git clone https://github.com/junegunn/fzf.git ~/tools-personal/fzf

~/tools-personal/fzf/install

fi
